<!DOCTYPE html>
<html>

<head>
    <title>Rider Performance Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo"
                        style="height: 70px; margin-bottom: 5px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>Rider Perfomance Report</strong></h2>
                    <h4>
                        @if ($startDate && $endDate)
                            From: {{ $startDate }} To {{ $endDate }}
                        @else
                            All Dates
                        @endif
                    </h4>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th style="text-align: left;">User Name</th>
                    <th>Total Shipments</th>
                    <th style="text-align: right;">Total Amount (KES)</th>
                    <th style="text-align: right;">Total Volume (KG)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($report as $index => $item)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td style="text-align: left;">{{ $item->name }}</td>
                        <td>{{ $item->total_shipments }}</td>
                        <td style="text-align: right;">{{ number_format($item->total_amount, 2) }}</td>
                        <td style="text-align: right;">{{ number_format($item->total_volume, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>

</html>
