<!DOCTYPE html>
<html>

<head>
    <title>Vehicle Performance Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .td-right {
            text-align: right;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo"
                        style="height: 70px; margin-bottom: 5px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>Vehicle Perfomance Report</strong></h2>
                    <h4>
                        @if ($startDate && $endDate)
                            From: {{ $startDate }} To {{ $endDate }}
                        @else
                            All Dates
                        @endif
                    </h4>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table border="1" cellspacing="0" cellpadding="5" width="100%">
            <thead>
                <tr>
                    <th>Transporter</th>
                    <th>Truck Reg No</th>
                    <th>Total Trips</th>
                    <th>Total Waybills</th>
                    <th>Total Quantity</th>
                    <th>Total Weight</th>
                    <th>Total Volume (KG)</th>
                    <th>Total Amount (KES)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($report as $row)
                    <tr>
                        <td>{{ $row->transporter_name }}</td>
                        <td>{{ $row->reg_no }}</td>
                        <td class="td-right">{{ $row->total_trips ?? 0 }}</td>
                        <td class="td-right">{{ $row->total_waybills ?? 0 }}</td>
                        <td class="td-right">{{ $row->total_quantity ?? 0 }}</td>
                        <td class="td-right">{{ number_format($row->total_weight ?? 0) }}</td>
                        <td class="td-right">{{ number_format($row->total_volume ?? 0) }}</td>
                        <td class="td-right">{{ number_format($row->total_amount ?? 0, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</body>

</html>
