<!DOCTYPE html>
<html>

<head>
    <title>Shipment Arrivals Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table>
            <tr>
                <td style="text-align: center; vertical-align: top;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px;">
                </td>
            </tr>
            <tr>
                <td style="text-align: center;">
                    <h1><strong>Parcel Receipts Report {{ $titled }} at {{ Auth::user()->office->name }} </strong>
                    </h1>
                </td>

            </tr>
            <tr style="margin-bottom:20px !important">
                <td>
                    <div style="width: 100%; ">
                        <div style="float: left;">
                            <p style="margin: 0;">
                                <strong>Reporting Period:</strong>
                                {{ \Carbon\Carbon::now()->format('F j, Y \a\t g:i A') }}
                            </p>
                        </div>
                        <div style="float: right; text-align: right;">
                            <p style="margin: 0;">
                                <strong>Reporting Generated By:</strong>
                                {{ \Carbon\Carbon::now()->format('F j, Y \a\t g:i A') }}
                            </p>
                        </div>
                    </div>
                </td>
            </tr>

        </table>

        <!-- Main Table -->
        <table class="bordered" style="margin-top:30px">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Manifest No.</th>
                    <th>Dispatch date</th>
                    <th>Office of Origin</th>
                    <th>Destination</th>
                    <th>Vehicle Number</th>
                    <th>Transporter</th>
                    <th>Driver</th>
                    <th style="text-align:right">Amount</th>
                    <th>Date Received</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($sheets as $sheet)
                    <tr>
                        <td>{{ $loop->iteration }}.</td>
                        <td class="text-danger sized">{{ str_pad($sheet->batch_no, 5, '0', STR_PAD_LEFT) }}</td>
                        <td> {{ $sheet->dispatch_date ?? 'Pending Dispatch' }} </td>
                        <td> {{ $sheet->office->name }} </td>
                        <td> {{ $sheet->rate->destination ?? '' }} @if ($sheet->destination_id == '0')
                                {{ 'Various' }}
                            @endif
                        </td>
                        <td> {{ $sheet->transporter_truck->reg_no }} </td>
                        <td> {{ $sheet->transporter->name }} </td>
                        <td>{{ $sheet->transporter_truck->driver_name }}</td>
                        <td>{{ $sheet->amount }}</td>
                        <td>{{ $sheet->received_date }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>

</html>
