<!DOCTYPE html>
<html>

<head>
    <title>COD Management Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table>
            <tr>
                <td style="text-align: center; vertical-align: top;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px;">
                </td>
            </tr>
            <tr>
                <td style="text-align: center;">
                    <h1><strong>COD Management Report {{ $titled }} at {{ Auth::user()->office->name }} </strong>
                    </h1>
                </td>

            </tr>
            <tr style="margin-bottom:20px !important">
                <td>
                    <div style="width: 100%; ">
                        <div style="float: left;">
                            <p style="margin: 0;">
                                <strong>Reporting Period:</strong>
                                {{ \Carbon\Carbon::now()->format('F j, Y \a\t g:i A') }}
                            </p>
                        </div>
                        <div style="float: right; text-align: right;">
                            <p style="margin: 0;">
                                <strong>Reporting Generated By:</strong>
                                {{ Auth::user()->name }}
                            </p>
                        </div>
                    </div>
                </td>
            </tr>

        </table>

        <!-- Main Table -->
        <table class="bordered" style="margin-top:30px">
            <thead>
                <tr>
                    <th>Amount Collected</th>
                    <th>Request ID</th>
                    <th>Collected By</th>
                    <th>Date Collected</th>
                    <th>Collection Balance</th>
                    <th>Amount Received</th>
                    <th>Receiver Remarks</th>
                    <th>Received By</th>
                    <th>Date Received</th>
                    <th>Received Balance</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($cods as $cod)
                    @php
                        $actualAmount = 0;
                        if ($cod->shipment) {
                            $actualAmount =
                                ($cod->shipment->actual_total_cost ?? 0) +
                                ($cod->shipment->last_mile_delivery_charges ?? 0);
                        }
                    @endphp
                    <tr>
                        <td>{{ number_format($cod->amountCollected, 2) }}</td>
                        <td>{{ $cod->requestId }}</td>
                        <td>{{ $cod->collector->name ?? 'N/A' }}</td>
                        <td>{{ $cod->dateCollected }}</td>
                        <td>{{ number_format($cod->collectionBalance, 2) }}</td>
                        <td>{{ number_format($cod->amountReceived, 2) }}</td>
                        <td>{{ $cod->receiverRemarks }}</td>
                        <td>{{ $cod->receiver->name ?? 'N/A' }}</td>
                        <td>{{ $cod->dateReceived }}</td>
                        <td>{{ number_format($cod->receicedBalance, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>

</html>
