<!DOCTYPE html>
<html>

<head>
    <title>Client Shipment Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px; margin-bottom: 10px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>{{ $reportTitle }}</strong></h2>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ auth('client')->user()->name }} </p>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Request ID</th>
                    <th>Date</th>
                    <th>Service Level</th>
                    <th>Items</th>
                    <th>Assigned rider & truck</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Receiver</th>
                    <th>Collection Status</th>
                    <th style="text-align: right;">Amount (Ksh)</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($clientRequests as $collection)
                    <tr>
                        <td>{{ $loop->iteration }}.</td>
                        <td>{{ $collection->requestId }}</td>
                        <td data-date="{{ $collection->dateRequested }}">
                            {{ \Carbon\Carbon::parse($collection->dateRequested)->format('M d, Y') ?? null }}
                        </td>
                        <td>{{ \Illuminate\Support\Str::title($collection->serviceLevel->sub_category_name ?? null) }}</td>
                        <td>{{ $collection->shipmentCollection?->items?->count() ?? '' }}</td>
                        <td>{{ optional($collection->user)->name ? optional($collection->user)->name . ' | ' . optional($collection->vehicle)->regNo : 'Pending' }}</td>
                        <td>{{ $collection->shipmentCollection->sender_town ?? '' }}</td>
                        <td>{{ $collection->shipmentCollection->receiver_town ?? '' }}</td>
                        <td>{{ $collection->shipmentCollection->receiver_name ?? '' }}</td>
                        <td>{{ $collection->status ?? '' }}</td>
                        <td style="text-align: right;"> {{ number_format($collection->shipmentCollection?->actual_total_cost, 2) }} </td>
                    </tr>
                @empty
                    <tr><td colspan="13" class="text-center">No records found</td></tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="10" style="text-align: right;">Total</th>
                    <th style="text-align: right;">
                        {{ number_format(
                            $clientRequests->sum(fn ($request) => $request->shipmentCollection?->actual_total_cost ?? 0),
                            2
                        ) }}
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>
</body>

</html>
