<!DOCTYPE html>
<html>

<head>
    <title>Overnight Parcels PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }

        h3 {
            font-size: 20px !important;
        }

        .lead {
            font-size: 16px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table>
            <tr>
                <td style="text-align: center; vertical-align: top;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px;">
                </td>
            </tr>
            <tr>
                <td style="text-align: center;">
                    <h1><strong>Report for All Overnight Parcels for {{ auth('client')->user()->name }}</strong></h1>
                </td>

            </tr>
            <tr style="margin-bottom:20px !important">
                <td>
                    <div style="width: 100%; ">
                        <div style="float: left;">
                            @php
                                $start = request('start');
                                $end = request('end');
                            @endphp

                            @if($start && $end)
                                <p style="margin: 0;"><strong>Report Period:</strong>
                                    {{ \Carbon\Carbon::parse($start)->format('F j, Y') }} – {{ \Carbon\Carbon::parse($end)->format('F j, Y') }}
                                </p>
                            @elseif($start && !$end)
                                <p style="margin: 0;"><strong>Report Period:</strong>
                                    From {{ \Carbon\Carbon::parse($start)->format('F j, Y') }}
                                </p>
                            @elseif(!$start && $end)
                                <p style="margin: 0;"><strong>Report Period:</strong>
                                    Up to {{ \Carbon\Carbon::parse($end)->format('F j, Y') }}
                                </p>
                            @else
                                <p style="margin: 0;"><strong>Report Period:</strong> All Dates</p>
                            @endif
                        </div>
                        <div style="float: right; text-align: right;">
                            <p style="margin: 0;">
                                <strong>Reporting Generated By:</strong>
                                {{ auth('client')->user()->name }}
                            </p>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered" style="margin-top:30px">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Request ID</th>
                    <th>Client</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Date Requested</th>
                    <th>Description</th>
                    <th style="text-align: right;">Amount (Ksh)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($clientRequests as $request)
                    <tr>
                        <td> {{ $loop->iteration }}. </td>
                        <td> {{ $request->requestId }} </td>
                        <td> {{ $request->client->name }} </td>
                        <td> {{ $request->shipmentCollection?->sender_town }} </td>
                        <td> {{ $request->shipmentCollection?->receiver_town }} </td>
                        <td> {{ \Carbon\Carbon::parse($request->dateRequested)->format('M j, Y') }}
                        </td>
                        <td> {{ $request->parcelDetails }} </td>
                        <td style="text-align: right;"> {{ number_format($request->shipmentCollection?->actual_total_cost, 2) }} </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>

</html>
