<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>User Log Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        h2 {
            margin: 0;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        table th {
            background: #f2f2f2;
        }

        .footer {
            width: 100%;
            clear: both;
            margin-top: 20px;
            font-size: 12px;
        }

        .footer .left {
            float: left;
            margin: 0;
            padding: 0;
        }

        .footer .right {
            float: right;
            margin: 0;
            padding: 0;
        }
    </style>
</head>

<body>
    <table>
        <tr>
            <td style="text-align: left;">
                <h2>User Activity Log Report</h2>
                <p><strong>User:</strong> {{ $user }}</p>
                <p><strong>Date:</strong> {{ $date }}</p>
                {{-- <p><strong>Reporting Period:</strong> {{ \Carbon\Carbon::now()->format('F j, Y \a\t g:i A') }}</p> --}}
            </td>
            <td style="text-align: right; vertical-align: top;">
                <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px;">
            </td>
        </tr>
    </table>

    <table class="bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Time</th>
                <th>Action Taken</th>
                <th>URL Visited</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($logs as $i => $log)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ \Carbon\Carbon::parse($log->created_at)->format('H:i:s') }}</td>
                    <td>{{ $log->actions }}</td>
                    <td>{{ $log->url }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p class="left">Generated on {{ now()->format('Y-m-d H:i:s') }}</p>
        <p class="right">
            Generated by {{ Auth::user()->name ?? 'System' }}</p>
    </div>

</body>

</html>
