<!DOCTYPE html>
<html>

<head>
    <title>Report for Same Day Rates From Nairobi to other Destinations PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }

        h3 {
            font-size: 20px !important;
        }

        .lead {
            font-size: 16px;
        }

        .text-right {
            text-align: right !important;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table>
            <tr>
                <td style="text-align: left;">
                    <h3><strong>Report for Same Day Rates From Nairobi to other Destinations</strong></h3>
                    <p class="lead"><strong>Reporting Period:</strong>
                        {{ \Carbon\Carbon::now()->format('F j, Y \a\t g:i A') }}</p>

                </td>
                <td style="text-align: right; vertical-align: top;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px;">
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th>Origin</th>
                    <th>Destination</th>
                    <th>Band</th>
                    <th class="text-right">Rate</th>
                    <th>From</th>
                    <th>To</th>
                    <th class="text-right">Additional Per KG</th>
                    <th>Approval Status</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($rates as $i => $rate)
                    <tr>
                        <td>{{ $loop->iteration }}.</td>
                        <td> {{ $rate->office->name }} </td>
                        <td> {{ $rate->destination }} </td>
                        <td>{{ $rate->bands }}</td>
                        <td class="text-right"> {{ number_format($rate->rate, 2) }} </td>
                        <td> {{ \Carbon\Carbon::parse($rate->applicableFrom)->toDateString() }} </td>
                        <td> {{ $rate->applicableTo ? \Carbon\Carbon::parse($rate->applicableTo)->toDateString() : '' }}
                        </td>
                        <td class="text-right"> {{ number_format($rate->additional_kg, 2) }} </td>
                        <td> {{ $rate->approvalStatus }} </td>
                        <td> {{ $rate->status }} </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <p class="lead text-right">Generated By: {{ Auth::user()->name }}</p>
    </div>
</body>

</html>
