<!DOCTYPE html>
<html>

<head>
    <title>Client Performance Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px; margin-bottom: 10px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>Client Performance Report</strong></h2>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead class="text-success">
                <tr>
                    <th>#</th>
                    <th>Client Name</th>
                    <th style="text-align: center;">Shipments (#)</th>
                    <th style="text-align: center;">Total Weight (Kg)</th>
                    <th style="text-align: right;">Revenue (Ksh)</th>
                    <th style="text-align: right;">Avg. Revenue/Shipment (Ksh)</th>
                    <!-- <th>Payment mix</th> -->
                </tr>
            </thead>
            <tbody class="text-primary">
                @forelse ($clients as $client)
                    <tr>
                        <td>{{ $loop->iteration }}.</td>
                        <td>{{ $client->name }}</td>
                        <td style="text-align: center;">{{ $client->items_count }}</td>
                        <td style="text-align: center;">{{ $client->total_weight ?? 0 }}</td>
                        <td style="text-align: right;">{{ number_format($client->total_revenue ?? 0, 2) }}</td>
                        <td style="text-align: right;">{{ number_format($client->avg_revenue_per_shipment ?? 0, 2)}}</td>
                        <!-- <td>
                            @foreach($client->payment_mix as $mode => $percentage)
                                {{ $mode }}: {{ $percentage }} <br>
                            @endforeach
                        </td> -->
                    </tr>
                @empty
                    <tr><td colspan="13" class="text-center">No records found</td></tr>
                @endforelse
            </tbody>
            <tfoot class="text-success">
                <tr>
                    <th>#</th>
                    <th>Client Name</th>
                    <th style="text-align: center;">Shipments (#)</th>
                    <th style="text-align: center;">Total Weight (Kg)</th>
                    <th style="text-align: right;">Revenue (Ksh)</th>
                    <th style="text-align: right;">Avg. Revenue/Shipment (Ksh)</th>
                    <!-- <th>Payment mix</th> -->
                </tr>
            </tfoot>
        </table>
    </div>
</body>

</html>
