<!DOCTYPE html>
<html>

<head>
    <title>Dispatch Summary Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px; margin-bottom: 5px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>Dispatch Summary Report</strong></h2>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Office</th>
                    <th style="text-align: center;">Total Dispatches</th>
                    <th style="text-align: right;">Total Shipments</th>
                    <th style="text-align: right;">Total Weight (kg)</th>
                    <th style="text-align: right;">Total Revenue (Ksh)</th>
                    <th style="text-align: center;">Avg Revenue/Shipment (Ksh)</th>
                    <!-- <th>Payment Mix</th> -->
                    <th style="text-align: right;">Premium Services</th>
                    <!-- <th>Destination Breakdown</th> -->
                </tr>
            </thead>
            <tbody>
                @forelse ($offices as $office)
                    <tr>
                        <td>{{ $loop->iteration }}.</td>
                        <td>{{ $office->name }}</td>
                        <td style="text-align: center;">{{ $office->total_dispatches }}</td>
                        <td style="text-align: right;">{{ $office->total_shipments }}</td>
                        <td style="text-align: right;">{{ number_format($office->total_weight, 2) }}</td>
                        <td style="text-align: right;">{{ number_format($office->total_revenue, 2) }}</td>
                        <td style="text-align: center;">{{ number_format($office->avg_revenue_per_shipment, 2) }}</td>
                        <!-- <td>
                            @foreach($office->payment_mix as $mode => $percentage)
                                {{ $mode ?? 'N/A' }}: {{ $percentage }}% <br>
                            @endforeach
                        </td> -->
                        <td style="text-align: right;">{{ $office->premium_services }}</td>
                        <!-- <td>
                            <ul class="mb-0">
                                @foreach($office->destination_breakdown as $dest)
                                    <li>{{ $dest['office'] }}: {{ $dest['shipments'] }} (KES {{ number_format($dest['revenue'], 2) }})</li>
                                @endforeach
                            </ul>
                        </td> -->
                    </tr>
                @empty
                    <tr><td colspan="13" class="text-center">No records found</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
</body>

</html>
