<!DOCTYPE html>
<html>

<head>
    <title>Office Performance Detail - {{ $office->name }}</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }

        .summary-table {
            width: 100%;
            margin-top: 6px;
            border: 1px solid #000;
            border-collapse: collapse;
        }

        .summary-table td {
            padding: 5px;
            border: 1px solid #000;
        }

        .summary-table th {
            text-align: left;
            background-color: #f2f2f2;
            padding: 5px;
            border: 1px solid #000;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px; margin-bottom: 5px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>Office Performance Detail</strong></h2>
                    <h3><strong>{{ $office->name }}</strong></h3>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
                </td>
            </tr>
        </table>

        <!-- Summary Section -->
        <table class="summary-table">
            <tr>
                <th>Total Shipments</th>
                <td>{{ $shipments->count() }}</td>
                <th>Total Weight (Kg)</th>
                <td>{{ number_format($shipments->sum('total_weight'), 2) }}</td>
            </tr>
            <tr>
                <th>Total Revenue (Ksh)</th>
                <td>Ksh {{ number_format($shipments->sum('actual_total_cost'), 2) }}</td>
                <th>Average Revenue/Shipment (KES)</th>
                <td>
                    @php
                        $count = $shipments->count();
                        $avg = $count > 0 ? $shipments->sum('actual_total_cost') / $count : 0;
                    @endphp
                    Ksh {{ number_format($avg, 2) }}
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Request ID</th>
                    <th>Consignment No</th>
                    <th>Waybill No</th>
                    <th>Receiver</th>
                    <th>Weight (Kg)</th>
                    <th style="text-align: right;">Revenue (Ksh)</th>
                    <th>Payment Mode</th>
                    <th>Status</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($shipments as $index => $shipment)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $shipment->requestId }}</td>
                        <td>{{ $shipment->consignment_no }}</td>
                        <td>{{ $shipment->waybill_no }}</td>
                        <td>{{ $shipment->receiver_name }} ({{ $shipment->receiver_phone }})</td>
                        <td style="text-align: center;">{{ $shipment->total_weight }}</td>
                        <td style="text-align: right;">{{ number_format($shipment->actual_total_cost, 2) }}</td>
                        <td>{{ $shipment->payment_mode }}</td>
                        <td>{{ ucfirst($shipment->status) }}</td>
                        <td>{{ \Carbon\Carbon::parse($shipment->created_at)->format('M d, Y') }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="10" style="text-align:center;">No shipments found for this office</td>
                    </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="5" style="text-align: right;">Totals:</th>
                    <th style="text-align: center;">{{ number_format($shipments->sum('total_weight'), 2) }}</th>
                    <th style="text-align: right;">Ksh {{ number_format($shipments->sum('actual_total_cost'), 2) }}</th>
                    <th colspan="3"></th>
                </tr>
            </tfoot>
        </table>
    </div>
</body>

</html>
