<!DOCTYPE html>
<html>

<head>
    <title>Office Performance Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px; margin-bottom: 5px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>Office Performance Report</strong></h2>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Office Name</th>
                    <th>Total Shipments</th>
                    <th>Total Weight (Kg)</th>
                    <th>Total Revenue</th>
                    <th>Avg. Revenue/Shipment</th>
                    <th>Payment mix</th>
                    <th>Premium parcels (Fragile/Priority)</th>
                </tr>
            </thead>
            <tbody class="text-primary">
                @forelse ($offices as $office)
                    <tr>
                        <td>{{ $loop->iteration }}.</td>
                        <td>{{ $office->name }}</td>
                        <td>{{ $office->total_shipments }}</td>
                        <td>{{ $office->total_weight }}</td>
                        <td>Ksh {{ number_format($office->total_revenue, 2) }}</td>
                        <td>Ksh {{ number_format($office->avg_revenue_per_shipment, 2) }}</td>
                        <td>
                            @foreach ($office->payment_mix as $mode => $percent)
                                {{ $mode }}: {{ $percent }}%<br>
                            @endforeach
                        </td>
                        <td>{{ $office->premium_services }}</td>
                    </tr>
                @empty
                    <tr><td colspan="13" class="text-center">No records found</td></tr>
                @endforelse
            </tbody>
            <tfoot class="text-success">
                <tr>
                    <th>#</th>
                    <th>Office Name</th>
                    <th>Total Shipments</th>
                    <th>Total Weight (Kg)</th>
                    <th>Total Revenue</th>
                    <th>Avg. Revenue/Shipment</th>
                    <th>Payment mix</th>
                    <th>Premium parcels (Fragile/Priority)</th>
                </tr>
            </tfoot>
        </table>
    </div>
</body>

</html>
