<!DOCTYPE html>
<html>

<head>
    <title>Shipment Report PDF</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin-left: 50px;
            margin-right: 20px;
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.bordered th,
        table.bordered td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        h2 {
            margin-bottom: 0;
        }

        @page {
            margin: 50px 30px;
        }

        .content {
            margin-bottom: 50px;
        }
    </style>
</head>

<body>
    <div class="content">
        <!-- Report Header -->
        <table style="width: 100%; text-align: center;">
            <tr>
                <td colspan="2" style="text-align: center;">
                    <img src="{{ public_path('images/UCSLogo1.png') }}" alt="Logo" style="height: 70px; margin-bottom: 10px;">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h2><strong>{{ $reportTitle }}</strong></h2>
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">
                    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                </td>
                <td style="text-align: right;">
                    <p><strong>Generated by:</strong> {{ Auth::user()->name }}</p>
                </td>
            </tr>
        </table>

        <!-- Main Table -->
        <table class="bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Request ID</th>
                    <th>Date</th>
                    <th>Consigner</th>
                    <th>Client Type</th>
                    <th>Consignee</th>
                    <th>Service level</th>
                    <th>Items</th>
                    <th>No. of packages</th>
                    <th>Assigned rider & truck</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Payment Terms</th>
                    <th>Collection status</th>
                    <th>Processed by</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($clientRequests as $collection)
                    <tr>
                        <td>{{ $loop->iteration }}.</td>
                        <td>{{ $collection->requestId }}</td>
                        <td data-date="{{ $collection->dateRequested }}">
                            {{ \Carbon\Carbon::parse($collection->dateRequested)->format('M d, Y') ?? null }}
                        </td>
                        <td>{{ $collection->client->name ?? '' }}</td>
                        <td>{{ $collection->client->type ?? '' }}</td>
                        <td>{{ $collection->shipmentCollection->receiver_name ?? '' }}</td>
                        <td>{{ $collection->serviceLevel->sub_category_name }}</td>
                        <td>{{ $collection->shipmentCollection?->items?->count() ?? '' }}</td>
                        <td>{{ $collection->shipmentCollection->packages_no ?? '' }}</td>
                        <td>{{ optional($collection->user)->name ? optional($collection->user)->name . ' | ' . optional($collection->vehicle)->regNo : 'Pending' }}</td>
                        <td>{{ $collection->shipmentCollection->sender_town ?? '' }}</td>
                        <td>{{ $collection->shipmentCollection->receiver_town ?? '' }}</td>
                        <td>{{ $collection->shipmentCollection->payment_mode ?? '' }}</td>
                        <td class="uppercase">{{ $collection->status ?? '' }}</td>
                        <td>{{ $collection->createdBy->name ?? 'N/A' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="13" class="text-center">No records found</td></tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th>#</th>
                    <th>Request ID</th>
                    <th>Date</th>
                    <th>Consigner</th>
                    <th>Client Type</th>
                    <th>Consignee</th>
                    <th>Service level</th>
                    <th>Items</th>
                    <th>No. of packages</th>
                    <th>Assigned rider & truck</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Payment Terms</th>
                    <th>Collection status</th>
                    <th>Processed by</th>
                </tr>
            </tfoot>
        </table>
    </div>
</body>

</html>
